//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMANA.SIGELIBMA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraLibro
    {
        public string Codigo { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int Categoria { get; set; }
        public int Autor { get; set; }
        public int Proveedor { get; set; }
        public decimal PrecioBase { get; set; }
        public decimal PorcentajeGanancia { get; set; }
        public decimal PrecioVentaSinImpuestos { get; set; }
        public decimal PrecioVentaConImpuestos { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> Estado { get; set; }
        public int TransaccionId { get; set; }
    
        public virtual Transaccion Transaccion { get; set; }
    }
}
