//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMANA.SIGELIBMA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Caja()
        {
            this.Factura = new HashSet<Factura>();
            this.MovimientoCaja = new HashSet<MovimientoCaja>();
        }
    
        public int Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Cajero { get; set; }
        public System.DateTime HoraApertura { get; set; }
        public Nullable<System.DateTime> HoraCierre { get; set; }
        public decimal MontoApertura { get; set; }
        public Nullable<decimal> MontoCierre { get; set; }
        public int Estado { get; set; }
    
        public virtual EstadoCaja EstadoCaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoCaja> MovimientoCaja { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
