//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMANA.SIGELIBMA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajaUsuario
    {
        public int Sesion { get; set; }
        public int Caja { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Apertura { get; set; }
        public Nullable<System.DateTime> Cierre { get; set; }
        public decimal MontoApertura { get; set; }
        public Nullable<decimal> MontoCierre { get; set; }
    
        public virtual Caja Caja1 { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
