//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMANA.SIGELIBMA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.DetalleFactura = new HashSet<DetalleFactura>();
            this.Recibo = new HashSet<Recibo>();
        }
    
        public int Numero { get; set; }
        public string Cliente { get; set; }
        public int Caja { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public decimal ImpuestoVenta { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Total { get; set; }
        public Nullable<decimal> Pendiente { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual Caja Caja1 { get; set; }
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
        public virtual EstadoFactura EstadoFactura { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Recibo> Recibo { get; set; }
    }
}
