//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMANA.SIGELIBMA.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIGELIBMAEntities : DbContext
    {
        public SIGELIBMAEntities()
            : base("name=SIGELIBMAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<Caja> Caja { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Descuento> Descuento { get; set; }
        public virtual DbSet<DetalleFactura> DetalleFactura { get; set; }
        public virtual DbSet<EstadoCaja> EstadoCaja { get; set; }
        public virtual DbSet<EstadoFactura> EstadoFactura { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Libro> Libro { get; set; }
        public virtual DbSet<Moneda> Moneda { get; set; }
        public virtual DbSet<MovimientoCaja> MovimientoCaja { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Recibo> Recibo { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Sesion> Sesion { get; set; }
        public virtual DbSet<TipoMovimientoCaja> TipoMovimientoCaja { get; set; }
        public virtual DbSet<TipoTransaccion> TipoTransaccion { get; set; }
        public virtual DbSet<Transacion> Transacion { get; set; }
        public virtual DbSet<UsarioRoles> UsarioRoles { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
