//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMANA.SIGELIBMA.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIGELIBMAEntities : DbContext
    {
        public SIGELIBMAEntities()
            : base("name=SIGELIBMAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<BitacoraAutor> BitacoraAutor { get; set; }
        public virtual DbSet<BitacoraCaja> BitacoraCaja { get; set; }
        public virtual DbSet<BitacoraCategoria> BitacoraCategoria { get; set; }
        public virtual DbSet<BitacoraDeposito> BitacoraDeposito { get; set; }
        public virtual DbSet<BitacoraDescuento> BitacoraDescuento { get; set; }
        public virtual DbSet<BitacoraDetalleFactura> BitacoraDetalleFactura { get; set; }
        public virtual DbSet<BitacoraEstadoCaja> BitacoraEstadoCaja { get; set; }
        public virtual DbSet<BitacoraEstadoFactura> BitacoraEstadoFactura { get; set; }
        public virtual DbSet<BitacoraFactura> BitacoraFactura { get; set; }
        public virtual DbSet<BitacoraInventario> BitacoraInventario { get; set; }
        public virtual DbSet<BitacoraLibro> BitacoraLibro { get; set; }
        public virtual DbSet<BitacoraMovimientoCaja> BitacoraMovimientoCaja { get; set; }
        public virtual DbSet<BitacoraProveedor> BitacoraProveedor { get; set; }
        public virtual DbSet<BitacoraRecibo> BitacoraRecibo { get; set; }
        public virtual DbSet<BitacoraRol> BitacoraRol { get; set; }
        public virtual DbSet<BitacoraTipoMovimientoCaja> BitacoraTipoMovimientoCaja { get; set; }
        public virtual DbSet<BitacoraTipoPago> BitacoraTipoPago { get; set; }
        public virtual DbSet<BitacoraTipoTransaccion> BitacoraTipoTransaccion { get; set; }
        public virtual DbSet<BitacoraTransaccion> BitacoraTransaccion { get; set; }
        public virtual DbSet<BitacoraUsuario> BitacoraUsuario { get; set; }
        public virtual DbSet<BitacoraUsuarioRoles> BitacoraUsuarioRoles { get; set; }
        public virtual DbSet<Caja> Caja { get; set; }
        public virtual DbSet<CajaUsuario> CajaUsuario { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Deposito> Deposito { get; set; }
        public virtual DbSet<DetalleFactura> DetalleFactura { get; set; }
        public virtual DbSet<EstadoCaja> EstadoCaja { get; set; }
        public virtual DbSet<EstadoFactura> EstadoFactura { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<Libro> Libro { get; set; }
        public virtual DbSet<MovimientoCaja> MovimientoCaja { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Recibo> Recibo { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Sesion> Sesion { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoMovimientoCaja> TipoMovimientoCaja { get; set; }
        public virtual DbSet<TipoPago> TipoPago { get; set; }
        public virtual DbSet<TipoTransaccion> TipoTransaccion { get; set; }
        public virtual DbSet<Transaccion> Transaccion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioRoles> UsuarioRoles { get; set; }
    }
}
