//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMANA.SIGELIBMA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPago
    {
        public TipoPago()
        {
            this.Factura = new HashSet<Factura>();
        }
    
        public int Codigo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Factura> Factura { get; set; }
    }
}
