//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMANA.SIGELIBMA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioRoles
    {
        public string Usuario { get; set; }
        public int Rol { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual Rol Rol1 { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
